Remove version from configuration-as-code dependency
jenkinsci/configuration-as-code-groovy-plugin pull request #7
Opened 2022-09-10 12:59 UTC by pascal-hofmann

2023-06-20 06:11 UTC, pascal-hofmann commented
Hi @szandala, @jetersen!

Can I help to get this merged?

Cheers,
Pascal

2023-06-20 09:37 UTC, jetersen requested changes

2023-06-20 09:37 UTC, jetersen commented on pom.xml
> +        <version>4.46</version>
Why not the newest?

2023-06-20 09:37 UTC, jetersen commented on pom.xml
> +        <jenkins.version>2.319.3</jenkins.version>
This is a really old baseline, please consider the following.
https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/

2023-06-20 09:37 UTC, jetersen commented on pom.xml
> +        <plugin-bom.version>1607.va_c1576527071</plugin-bom.version>
property is not needed just move it to where it is used.

2023-06-20 12:00 UTC, jetersen commented
Did not notice the PR before you pinged but I would like to see these values updated at least. :)

2023-06-20 14:40 UTC, pascal-hofmann commented
Hi @jetersen,
by now I completely forgot what I did here and why. 😅 

I tried to update my PR according to your comments. Can you have another look?

Cheers,
Pascal

2023-09-10 19:22 UTC, icep87 commented
@jetersen could you take a second look?

2023-09-11 06:00 UTC, jetersen approved these changes

2023-09-11 07:35 UTC, icep87 commented
@jetersen can you maybe trigger the tests once again and merge this pr?

2023-09-11 08:16 UTC, jetersen commented
I think the Jenkins file needs updating 🤕

2023-09-11 18:38 UTC, icep87 commented
@pascal-hofmann any chance you could take a look?

2024-01-05 16:32 UTC, pascal-hofmann commented
Sorry, this got buried under other things on my desk.

@jetersen Can you have another look? I assume my Jenkinsfile changes are not effective as I have not write access to the repo.

2024-01-08 08:19 UTC, pascal-hofmann commented
I just had a look at the logs. It really does ignore my Jenkinsfile. 

```
[2024-01-05T16:31:40.257Z] Loading trusted files from base branch master at fd4f71096564a24f600e723b3263c4f973347c19 rather than 5a62240a3aa9c82f08b50b31ce960d6764389757
[2024-01-05T16:31:40.385Z] Obtained Jenkinsfile from fd4f71096564a24f600e723b3263c4f973347c19
[2024-01-05T16:31:40.607Z] ‘Jenkinsfile’ has been modified in an untrusted revision
```

2024-01-17 05:24 UTC, pascal-hofmann commented
Hi @jetersen,
can you have another look?

Cheers
Pascal

2024-01-23 15:53 UTC, pascal-hofmann commented
Hi @szandala, @jetersen!

I fixed the jenkinsfile, but it's not used in the build because it's untrusted. I guess a maintainer needs to approve the changes so it gets used?

Cheers,
Pascal

2024-01-23 16:18 UTC, szandala approved these changes

2024-01-23 16:20 UTC, szandala commented
I will merge this, but revert if it fails

2024-01-23 16:20 UTC, merged

2024-01-23 16:26 UTC, pascal-hofmann commented
Hmpf, this did not work. :(

It's a bit hard to test for me, without permission on the pipeline. Would be great if someone could have a look.

Thanks in advance,
Pascal

2024-01-23 17:01 UTC, szandala commented
Tried here:
https://github.com/jenkinsci/configuration-as-code-groovy-plugin/pull/9
Will try to look :-/